#!/usr/bin/env bash
#MISE description="Run all linters"
#MISE depends=["check:markdown-format", "lint:actionlint", "lint:yamllint", "lint:rumdl", "lint:ts", "lint:typecheck", "lint:format", "lint:spell"]
set -euo pipefail
